# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows-nodejs20"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "actions/checkout"
        versions: [">=3.6.0"]