# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:

  # Run on all changes (PR and push) to the python binding
  # source/configuration files, except on the release branches, which
  # have their own workflow, which also publish to pypi/test.pypi.
  # Note that changes to the core libraries will *not*
  # trigger building the wheels. However, the main ci workflow does
  # build and test the bindings (for a single python version on a
  # single arch)

  push:
    branches-ignore:
      - RB-*
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '!connanfile.txt'
      - '.github/workflows/python-wheels.yml'
      - 'share/ci/scripts/imath_skbuild_plugin.py'
  pull_request:
    branches-ignore:
      - RB-*
    paths:
      - 'src/**'
      - '!connanfile.txt'
      - 'pyproject.toml'
      - '.github/workflows/python-wheels.yml'
      - 'share/ci/scripts/imath_skbuild_plugin.py'

permissions:
  contents: read

jobs:
  build_wheels:
    name: Python Wheels - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Python 
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools build pybind11
          
      - name: Create sdist
        # Only create it once.
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          pipx run build --sdist . --outdir wheelhouse
             
      - name: Build wheel
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_BEFORE_BUILD_LINUX: "pip install conan && conan profile detect && conan install . --build=missing -s compiler.libcxx=libstdc++11 --output-folder=_conan"
          CIBW_BEFORE_BUILD_MACOS: "pip install conan && conan profile detect && conan install . --build=missing  --output-folder=_conan"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install conan && conan profile detect && conan install . --build=missing  --output-folder=_conan"
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Build Python 3.8 through 3.12.
          # Skip python 3.7 since scikit-build-core requires 3.8+
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-win32 *_i686"
          CIBW_TEST_SKIP: "*-macosx*arm64"
          OPENEXR_TEST_IMAGE_REPO: "https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/main"
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz
